### ISSUE TITLE
Add a resource for Azure Service Principal credentials type

### ISSUE THREAD

**Issue by gitflo1** [taiidani/terraform-provider-jenkins#107]
The Jenkins [Azure Credentials Plugin](https://plugins.jenkins.io/azure-credentials/) provides the credential type Azure Service Principal. It enables users to manage various Azure Credentials types, such as Azure Service Principals or Azure Managed Identities. Currently, the Jenkins Terraform provider does not support those credential types.

At first, it would be nice, if the Azure Service Principal credential type is supported by this provider. Additional Azure credential types may follow in the future. Therefore, a new Terraform resource `jenkins_credential_azure_service_principal` should be introduced, providing the same attributes for managing an Azure Service Principal, as the Jenkins credential API for Azure Service Principals:
```
<com.microsoft.azure.util.AzureCredentials>
	<id>123</id>
	<scope>GLOBAL</scope>
	<description>blabla</description>
	<data>
		<subscriptionId/>
		<clientId/>
		<clientSecret/>
		<certificateId/>
		<tenant/>
		<azureEnvironmentName/>
		<serviceManagementURL/>
		<authenticationEndpoint/>
		<resourceManagerEndpoint/>
		<graphEndpoint/>
	</data>
</com.microsoft.azure.util.AzureCredentials>
```

A sample Terraform resource definition could look like this:
```
resource "jenkins_credential_azure_service_principal" "example_azure_service_principal" {
    name = "bla"
    folder = jenkins_folder.example.id
    description = "blabla"
    subscription_id = "123"
    client_id = "123"
    client_secret = "super-secret"
    tenant = "123"
}
```

**Comment by taiidani** [comment]
Released in https://github.com/taiidani/terraform-provider-jenkins/releases/tag/v0.10.0
