### ISSUE TITLE
Depends_on doesn't work with provider resources

### ISSUE THREAD

**Issue by hila3000** [taiidani/terraform-provider-jenkins#118]
Hi,

I have a resource to create Jenkins jobs-
```
resource "jenkins_job" "load_jobs" {
  for_each = fileset("${path.module}/jobs", "*")
  name     = each.value
  template = templatefile("${path.module}/jobs/${each.value}", {
    description = " ${each.value} Jenkins Job Created by Terraform"
  })
  depends_on = [helm_release.jenkins, helm_release.externaldns]
}
```

As you can see, I've set depends_on, on both the Jenkins helm chart and the externaldns resource that deploys the Jenkins A record to route53.

This is the provider config-
```
provider "jenkins" {
  server_url = "http://jenkins.domainname.net:8080/" 
  username   = "admin"           
  password   = kubernetes_secret.jenkins-users.data.jenkins-admin-password          
  ca_cert = ""                       
}
```

But when I try to deploy the jobs while the Jenkins is not deployed yet, I get-
`Error: Get "http://jenkins.domainname.net:8080/api/json": dial tcp: lookup jenkins.domainname.net on 10.110.111.200:53: no such host`
Only after I run `terraform apply` on the helm_release to deploy Jenkins and make sure external-dns already deployed so the Jenkins A record will get updated, then the error goes away and the resource gets applied (and jobs gets created).
Meaning - the depends_on doesn't work.

Is this a bug or a feature? :)
I assume it's related to the provider configuration - It needs to have the domain name available before trying to execute/evaluate anything under this provider, but there's no module output I can use for the server_url to make Terraform generate a "natural" dependency.

I got to have this dependency because I need to deploy the entire code in one run (vs. modular, as it currently works).

Please advise.
Thanks!

**Comment by taiidani** [comment]
This sounds like it may be related to https://github.com/hashicorp/terraform/issues/2430, in which `terraform` itself must initiate the `jenkins` provider at Plan time to inspect your resources, but cannot due to the Jenkins instance not being online yet.

There are a few solutions proposed in there -- the most common suggestion is to separate the `jenkins` provider resources from the resources deploying Jenkins (Helm) in separate root modules. I hope this helps!

**Comment by hila3000** [comment]
That's what I eventually did - separated states, so the first, dependent one, always run first. That solved it for me.
