### ISSUE TITLE
support defining credentials?

### ISSUE THREAD

**Issue by davidkarlsen** [taiidani/terraform-provider-jenkins#13]
Great provider!
How about supporting credentials, like https://github.com/piotrjaromin/terraform-provider-jenkins#credentials (seems outdated)

**Comment by taiidani** [comment]
Sounds like a good idea! I'll try to get a PR up in the next couple of days.

**Comment by taiidani** [comment]
@davidkarlsen Taking a stab at username credentials with #15. Could you give it a look and verify that it matches what you are looking for? If you'd like to test it locally and need help with that I'd be happy to provide instruction.

Once this is in I'll look into the additional credential types.

**Comment by davidkarlsen** [comment]
I'll try to get to it during the week. What I'm looking for is to define IAM creds in order to use ECR.

**Comment by davidkarlsen** [comment]
OK, great - this works when defining the credentials in a top-level folder, but not in a subfolder.
i.e.:
```

resource "jenkins_credential_username" "cred" {
  name     = "credential"
  folder   = "level1"
  username = "someuser"
  password = "somepw"
}
```

works



```
resource "jenkins_credential_username" "cred" {
  name     = "credential"
  folder   = "level1/level2"
  username = "someuser"
  password = "somepw"
}
```
does not

**Comment by timothymathison** [comment]
How straight-forward would it be to add additional credential types to this? One I am particularly interested in is the **AzureServicePrincipal** type. (Let me know if you'd like me to open a new issue for this)

**Comment by taiidani** [comment]
@timothymathison We're still working through some tweaks to fix folder-based bugs that came out of this initial credentials rollout, but other than that new additions would be welcome.

For something like **AzureServicePrincipal** could you file a new issue, and also mention the plugin which users would be required to install in order to support that type?

**Comment by taiidani** [comment]
Closing issue as the initial support for credentials is now present. I am accepting PRs and additional issues for credential types beyond the currently supported ones! See #25 for an example of a successful addition.
