### ISSUE TITLE
Improve `jenkins_job` resource

### ISSUE THREAD

**Issue by naitmare01** [taiidani/terraform-provider-jenkins#156]
Suggestion to improve the `jenkins_job ` resource is to generate the xml instead forcing us to send it in as a template file.

This is done on the `jenkins_folder `resource already and that can maybe serve as an inspiration.

**Comment by taiidani** [comment]
Agreed that this would be a helpful addition. We would likely need to leave the `jenkins_job` resource as-is though. Any attempts to render XML (folders included) in an opinionated manner will introduce friction with Jenkins' plugin system since it adds dynamic elements to a job's XML schema.

**Comment by abrockmeyer-govtact** [comment]
@taiidani I would suggest having splitting the jenkins_job resource into two called "create_job_from_xml_template" that can be used for a job that's already in xml format and "create_job_from_pipeline" that could take in an xml template as a parameter to the job but contains a basic one that can be used from the get-go.
