### ISSUE TITLE
Support for SAML based authentication.

### ISSUE THREAD

**Issue by qu884j** [taiidani/terraform-provider-jenkins#22]
Great provider!

How about supporting SAML based authentication? is that possible?

To give more context, I'm using SAML SSO to authenticate users to Jenkins and the provider currently supports only username/password authentication which in this case is not possible because of SAML-based authentication enabled as the default authentication method on Jenkins. 

Is it possible to support SAML-based authentication or are there any known workarounds?

**Comment by qu884j** [comment]
it seems it's working fine with SAML based auth :)

**Comment by taiidani** [comment]
@qu884j Excellent to hear that! My company uses GitHub OAuth so I'd have had a hard time testing a SAML-based setup. Glad to hear that it's working out of the box for you :)
