### ISSUE TITLE
Support for data resources

### ISSUE THREAD

**Issue by zahiar** [taiidani/terraform-provider-jenkins#26]
Hey, thanks for the provider!

I've just started to make use of this and wondered if you thought of possibly adding data resources for like the jenkins_folder for example something like:

```
data "jenkins_folder" "my-folder" {
  name = "some-random-folder"
}
```

Would make it super easy to reference existing items 🙂

**Comment by taiidani** [comment]
@zahiar Sounds like a great idea! I've got a backwards-incompatible refactor inbound in 0.7 -- will try to get some data sources in there 👍

**Comment by taiidani** [comment]
Folder support added in #24

**Comment by taiidani** [comment]
Remaining resources added in #28
