### ISSUE TITLE
JENKINS_SERVER_URL env variable is not respected

### ISSUE THREAD

**Issue by nfx** [taiidani/terraform-provider-jenkins#34]
Version: 0.7.0-beta2

```
Error: Missing required argument

  on ../../modules/jenkins-ci/main.tf line 12, in provider "jenkins":
  12: provider jenkins {}

The argument "server_url" is required, but no definition was found.
```

env vars are set:
```
JENKINS_PASSWORD=...
JENKINS_SERVER_URL=...
JENKINS_USERNAME=...
```

username and password work as they intend to.

please also adjust plugin documentation to have quotes around the resource and provider names, to be consistent with the rest of the ecosystem.

**Comment by taiidani** [comment]
@nfx Try using the `JENKINS_URL` env var for the URL. It looks like the docs do mention SERVER_URL once (which needs to be corrected per this issue) but the rest of it points out JENKINS_URL as the correct env var to specify.

**Comment by nfx** [comment]
@taiidani please update the docs in the next release then :-)
