### ISSUE TITLE
Need for jenkins_credential_secret

### ISSUE THREAD

**Issue by nfx** [taiidani/terraform-provider-jenkins#35]
Some of the things are just API keys and not username/password pairs. Please add `Secret text` credential type.

![image](https://user-images.githubusercontent.com/259697/110206240-ce78cd80-7e7c-11eb-974a-a67f2dbe6d8d.png)

**Comment by jaceq** [comment]
Opened PR for that: https://github.com/taiidani/terraform-provider-jenkins/pull/36

**Comment by nfx** [comment]
@jaceq thank you!

**Comment by taiidani** [comment]
@nfx The new resource should be available in v0.7.0-beta3, just released. All credit goes to @jaceq for his work in the PR!
