### ISSUE TITLE
Folder description is configured with mojibake

### ISSUE THREAD

**Issue by grv87** [taiidani/terraform-provider-jenkins#41]
Given:

```hcl
resource "jenkins_folder" "some_folder" {
  name        = "SOME_FOLDER"
  description = "Какое-то non-latin описание"
```

I see mojibake in folder description in Jenkins UI.
Something like this:
```
ÐÐ¾Ð¼ÐµÐ½ ÐÑÑÐµÑÐ½Ð¾ÑÑÑ ÐÐ
```

**Comment by grv87** [comment]
Also, on each run Terraform shows difference and tries to fix it - obviously, without any success

**Comment by grv87** [comment]
Also, I note that DEBUG/TRACE is not supported.
I can't see anything that is send to Jenkins and got back.

**Comment by taiidani** [comment]
Hi @grv87 -- this is interesting; I'm unable to recreate the behavior you are seeing. Can you reproduce this with a vanilla Jenkins installation, such as the Dockerized version created in the `example/` folder?
