### ISSUE TITLE
jenkins_job doesn't check for template existence

### ISSUE THREAD

**Issue by grv87** [taiidani/terraform-provider-jenkins#42]
`jenkins_job` doesn't check for template existence.

I get error 500 from Jenkins - but can't figure out what this means.
(With template, I also get 500)

**Comment by taiidani** [comment]
Please provide more information and if possible an example recreating this problem. `template` is a [required property](https://github.com/taiidani/terraform-provider-jenkins/blob/dae43669b323ee728e35d61b69559c8b44dbe641/jenkins/resource_jenkins_job.go#L37) on `jenkins_job` so it checking for existence isn't necessary -- Terraform itself will enforce that it needs to be present.

Could you provide a sample?

Regarding the 500 error, that's an unfortunate side effect of the underlying library we use. It does not propagate errors back from Jenkins and does not expose a method for us to extract that error message. The 500 is a generic "something went wrong" error.
