### ISSUE TITLE
jenkins::create - Error creating job for "ecr-token-generator" in folder /job/sre: 500

### ISSUE THREAD

**Issue by javierlopez-itech** [taiidani/terraform-provider-jenkins#51]
Hello,

First off, thank you so much for taking the time to working on this project, it's great!

I'm using it to create a new job but it seems like it's not working (the funny thing is I tried this provider a few weeks ago and it worked like a charm). Here is part of the code

```
resource "jenkins_folder" "sre" {
  name        = "sre"
  description = "SRE Jenkins Jobs"
}

resource "jenkins_job" "ecr-token-generator-job" {
  name     = "ecr-token-generator"
  template = file("${path.module}/ecr-auth-token-generator.xml")
  folder   = jenkins_folder.sre.id

  parameters = {
    description = "Regenerates the ECR tokens (only last 12 hours)"
  }
}
```

The folder is creating without any issues but it's failing to create the job.

**Comment by javierlopez-itech** [comment]
funny thing, even though I was passing a parameter to the template I wasn't using it, I've changed the template to use it and it works now, I was going through the log and I saw three times `template bounding` and `template bounded`, my gut feeling is there is some sort of bug in the code that enters a recursive loop if the template pre/post processed looks exactly the same.

Again, thanks for your time!

**Comment by MHoinkaBS** [comment]
Hello, 
I'm getting the same error while trying to create Jenkins job. 

Terraform: 
```
│ Error: jenkins::create - Error creating job for "vu_test_service" in folder version-upgrade: 500
│ 
│   with jenkins_job.regular_development_pipeline_job,
│   on res_jenkins_jobs.tf line 2, in resource "jenkins_job" "regular_development_pipeline_job":
│    2: resource "jenkins_job" "regular_development_pipeline_job" {
```

Jenkins logs: 

```Error while serving http://localhost:8080/job/version-upgrade/createItem
javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
(...)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
(...)
Caused: java.io.IOException: Failed to persist config.xml
(...)
```

In my template there is neither xml prolog nor any whitespace at the begining. 
I've also tried to use template without params - the result was the same. 
Parent folder in Jenkins exists (created in other module using this provider).  

I'm running out of ideas what else could be checked.

**Comment by MHoinkaBS** [comment]
Ok, it works. 
I had a variable with template path - path was passed as a literal and not as file :). After fixing the path, works fine. 
If anoyone encounter such problem, make sure you can see in plan whole xml in jenkins job resource.
