### ISSUE TITLE
0.8 release date?

### ISSUE THREAD

**Issue by zahiar** [taiidani/terraform-provider-jenkins#56]
Hey, when do we plan on releasing version 0.8?

I see that all the tickets linked to the milestone have been completed: https://github.com/taiidani/terraform-provider-jenkins/milestone/5?closed=1

**Comment by taiidani** [comment]
@zahiar Generally I do a rollup based on the amount of activity in a given month or two. If I know a painful backwards compatibility break is happening I usually take a bit longer to see if there are ways to help get users through it.

tl;dr if you think a 0.8 is warranted, I'm happy to cut the release!

**Comment by zahiar** [comment]
@taiidani yeah I think it's worth cutting a release as it's been a few months since the last one and there's no more outstanding tickets to do 🙂
