### ISSUE TITLE
Error: Failed to instantiate provider "jenkins" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by ttpp8794** [taiidani/terraform-provider-jenkins#6]
I encountered Error: Failed to instantiate provider "jenkins" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5] when running terraform plan. Below is the terraform version we are using.
Terraform v0.12.24
+ provider.jenkins (unversioned)
+ provider.tfe v0.16.0

I installed the provider with "go install github.com/taiidani/terraform-provider-jenkins" and copy it to terraform.d/plugins folder.

I also tried to pull the source code from this repo and compile the provider. But I got the same error when running terraform plan.

Any idea on what could cause this problem and how to fix it?

Thanks

**Comment by taiidani** [comment]
@ttpp8794 I think the provider hasn't been compiled against the newest Terraform 0.12 API. Will try and get it upgraded over the next few days!
