### ISSUE TITLE
Deprecate parameters in jenkins_job

### ISSUE THREAD

**Issue by taiidani** [taiidani/terraform-provider-jenkins#60]
While reviewing #57 the issue was brought up that the `parameters` property has trouble with imports since there is no [easy] way for the import logic to scrape the incoming XML to determine where the parameters are being rendered from.

In @zahiar's example, they are using Terraform's [template_file](https://registry.terraform.io/providers/hashicorp/template/latest/docs/data-sources/file) resource (or, in TF 0.12+, [built-in templatefile function](https://www.terraform.io/docs/language/functions/templatefile.html)) to render their XML while still supporting parameters. I feel like `templatefile` completely absorbs the use cases that `parameters` originally fulfilled.

Consider deprecating and later removing the `parameters` property, then updating the documentation for `jenkins_job` to include an example demonstrating use of `templatefile` to achieve the same effect.

**Comment by zahiar** [comment]
Yep I agree. Over the past week, I've been working on an internal Terraform module to create pipelines, and I'm using `templatefile` as well now - did a refactor (we are on Terraform 1.0), works wonderfully 😃 

Example code

```
resource "jenkins_job" "build" {
  for_each = toset(var.environments)

  name   = "build"
  folder = jenkins_job.environment[each.key].id
  template = templatefile(
    "${path.module}/templates/build.xml",
    merge(
      local.common-template-vars,
      {
        environment = each.key
      }
    )
  )

  depends_on = [jenkins_job.checkout]
}
```

Slightly going off topic, I do seem to hit some unclean subsequent plans with benign changes, not fully sure why it happens 🤔  (if I update my template to match, then on subsequent plans, it will want to revert back to what I originally had - it's really strange 😞)

```
-       <command>export PROJECT=$(echo ${JOB_NAME} | cut -f2 -d &apos;/&apos;)
+       <command>export PROJECT=$(echo ${JOB_NAME} | cut -f2 -d '/')
```

```
-       <paramsToUseForLimit/>
+       <paramsToUseForLimit></paramsToUseForLimit>
```
