### ISSUE TITLE
Unescape HTML entities for a cleaner diff?

### ISSUE THREAD

**Issue by zahiar** [taiidani/terraform-provider-jenkins#62]
I've been hitting an issue whereby no matter what I have in my template XML file, it always shows an unclean diff when it comes to HTML entities. I've tried changing my template XML file to match but that doesn't seem to work 😢 

Examples:

Template file
```xml
    <hudson.tasks.Shell>
      <command>export PROJECT=$(echo $${JOB_NAME} | cut -f2 -d '/')</command>
    </hudson.tasks.Shell>
```

Plan output
```diff
-       <command>export PROJECT=$(echo ${JOB_NAME} | cut -f2 -d &apos;/&apos;)</command>
+       <command>export PROJECT=$(echo ${JOB_NAME} | cut -f2 -d '/')</command>
```

===> And the reverse <===

Template file
```xml
    <hudson.tasks.Shell>
      <command>export PROJECT=$(echo $${JOB_NAME} | cut -f2 -d &apos;/&apos;)</command>
    </hudson.tasks.Shell>
```

Plan output
```diff
-       <command>export PROJECT=$(echo ${JOB_NAME} | cut -f2 -d '/')</command>
+       <command>export PROJECT=$(echo ${JOB_NAME} | cut -f2 -d &apos;/&apos;)</command>
```

@taiidani An option I've been testing locally that solves this issue, is to unescape the HTML entities by adding this to the `templateDiff` function.
```
diff --git a/jenkins/util.go b/jenkins/util.go
--- a/jenkins/util.go	(revision 3730a0118fb9e2d7375370f612199d5e53ba11fc)
+++ b/jenkins/util.go	(date 1629585568050)
@@ -3,6 +3,7 @@
 import (
 	"context"
 	"fmt"
+	"html"
 	"log"
 	"regexp"
 	"strings"
@@ -83,9 +84,11 @@
 	old = re.ReplaceAllString(old, "")
 	old = strings.Replace(old, " ", "", -1)
 	old = strings.TrimSpace(old)
+	old = html.UnescapeString(old)
 	new = re.ReplaceAllString(new, "")
 	new = strings.Replace(new, " ", "", -1)
 	new = strings.TrimSpace(new)
+	new = html.UnescapeString(new)
 
 	log.Printf("[DEBUG] jenkins::diff - Old: %q", old)
 	log.Printf("[DEBUG] jenkins::diff - New: %q", new)
```

What do you think? Good idea? Bad idea? (I can't think of any downsides to this approach) - I'll throw up a PR if we're happy to do this.

**Comment by taiidani** [comment]
To add extra context to this, I was able to (on `main`) `apply` the template without escaped entities to the example Jenkins setup and have the subsequent `apply` show no changes required. That said, after I went into Jenkins and reconfigured the job (no changes, I just hit "Save") Jenkins itself saved the template with the entities escaped and generated the diff.

So from my perspective we're looking at a difference in how Jenkins wants to store the config (escaped) versus how the Provider wants to store the config (unescaped). I'm not 100% sure that making our diff more lenient is the best option over shifting the Provider to always expect escaped configs, but given how squirrely Jenkins is in its config structure I can't imagine that being more lenient would hurt.

Going to mention this concern in the linked PR and then approve it 👍

**Comment by zahiar** [comment]
If Jenkins (or perhaps it's the underlying plugins mis-managing their XML config 🤷) was consistent, be it to store them escaped all the time or unescaped all the time (I've seen it flip between them after just hitting "Save" without me changing anything 🙈), then definitely, Provider should be updated to match 💯 

But yeah, thanks for approval. I don't think we have anything left in our 0.9 milestone, so feel free to cut a release. If anything else crops up for me, I'll target that at our next milestone be it 0.10 or we could go the distance and jump to 1.0.0 🤩
