### ISSUE TITLE
0.9 release

### ISSUE THREAD

**Issue by zahiar** [taiidani/terraform-provider-jenkins#65]
@taiidani I think we've done enough to cut a release. If you'd like I'm happy to cut one, I think it's just creating a tag and that should kick off the release workflow.

**Comment by taiidani** [comment]
Sorry, just trying to find the time this week to do it. Yes, it's essentially:
1. Push a tag from the HEAD of `main`
2. Wait for goreleaser to build a GitHub Release
3. Edit the release with a human-readable description alongside the automated changelog

**Comment by zahiar** [comment]
No need to apologise, I'll happily do this for you 😃

**Comment by zahiar** [comment]
Above all done (feel free to look over and amend 🙂), https://github.com/taiidani/terraform-provider-jenkins/releases/tag/v0.9.0

I'll wait for it to appear in the public Terraform Registry before I close out this ticket and ultimately the milestone.

**Comment by zahiar** [comment]
Yep, it's on the public registry
https://registry.terraform.io/providers/taiidani/jenkins/0.9.0

**Comment by taiidani** [comment]
LGTM! Thanks for taking the initiative on this!
